services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5441:5432
    env_file:
      ./postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p $$POSTGRES_PORT"]
      interval: 10s
      retries: 5
      start_period: 1s
      timeout: 5s
